export enum Signo{
    SUMA="SUMA",
    RESTA="RESTA",
    DIVISION="DIVISION",
    MULTIPLICACION="MULTIPLICACION",
    POTENCIA="POTENCIA",
    MODULO="MODULO",
    NOT="NOT",
    OR="OR",
    AND="AND",
    MENOR="MENOR",
    MAYOR="MAYOR",
    MENORI="MENORIGUAL",
    MAYORI="MAYORIGUAL",
    IGUAL_IGUAL="IGUAL_IGUAL",
    DISTINTO="DISTINTO",
    TRIPLE_IGUAL="TRIPLE_IGUAL"
}